name: Deploy azure policy
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: "policy"
  cancel-in-progress: false

jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create or update Azure Policies
        uses: azure/manage-azure-policy@v0
        with:
          paths: |
            policies/**
